### ISSUE TITLE
Persian Lang

### ISSUE THREAD

**Issue by sajaddp** [puikinsh/Dazzling#12]
Hi,
I create Persian (Farsi) language for this theme.
Please add it to theme :)
http://up.rafsang.com/do.php?filename=26_151424987215831.rar

**Comment by puikinsh** [comment]
Sorry for late response. Just returned from vacation. 
Could you please reupload translation files as your link appear to be broken. 

Sorry for inconvenience.

**Comment by sajaddp** [comment]
just for u :)
http://www.freeuploadsite.com/do.php?id=67062

**Comment by sajaddp** [comment]
just for U :)
http://www.freeuploadsite.com/do.php?id=67062

**Comment by puikinsh** [comment]
I have added your translation on Github repository and have added you on colorlib contributor page that you can see it here: http://colorlib.com/wp/contributors/

Thank you for your time and effort to make this theme even better. Thank you!
