### ISSUE TITLE
Cross sells and up sells

### ISSUE THREAD

**Issue by nickcoupland** [puikinsh/Dazzling#13]
Hi, I was just trying to get cross sells and up sells working with this theme however neither are showing on the front end. Does this theme support that functionality?
Thanks

**Comment by puikinsh** [comment]
Both are working fine and you can even preview it in action on our demo website that you can see here: http://colorlib.com/dazzling/shop/

**Comment by nickcoupland** [comment]
Thank you for the reply. I am still having issues. I have disabled all plugins (except woocommerce) and made sure I'm using the default woocommerce templates and I still see no cross sell items. I have also made sure the product has cross sells items specified in the wp backend. Is there another woocommerce setting that I am missing?

**Comment by FreeWPTP** [comment]
@nickcoupland  It's the old thread so want to know are you still facing the issue?

If yes then you can get more in detail help from our support forum here https://colorlib.com/wp/forums/forum/dazzling/
