### ISSUE TITLE
How do i set Site Name Color

### ISSUE THREAD

**Issue by kurodz** [puikinsh/Dazzling#15]
How do i set Site Name Color ?

It always Green .

I cant find any option in Theme Option.

**Comment by puikinsh** [comment]
You can change it via Appearance >> Customize >> Color >> Header Text Color. 

I see that live preview is not working for this options but options itself is working fine. Will make sure to fix live preview as well.

**Comment by kurodz** [comment]
This is the only option i got :(
![](http://i.imgur.com/Ku2eTAH.png)

**Comment by puikinsh** [comment]
That's strange. 

Maybe try to download the latest version of this theme that you can find on Github - 1.5.2 to be exact.

**Comment by kurodz** [comment]
It Works !! Thanks.
I updated the theme from Wordpress Dashborad , maybe that's the problem.
