### ISSUE TITLE
flexSlider height is 0px onload

### ISSUE THREAD

**Issue by dimanise** [puikinsh/Dazzling#18]
Using 1 slider post, I get flexSlider div as 0px most of the time after load (using big image).

With this post https://github.com/woothemes/FlexSlider/issues/278 I was able to put .flexslider init into window.onload instead of document.ready so it waits after all images are loaded, and it fixes the issue.

Here's my code for inc/js/main.js:

jQuery(document).ready(function(t){t('#submit, .wpcf7-submit, .comment-reply-link, input[type="submit"]').addClass("btn btn-default"),t(".wp-caption").addClass("thumbnail"),t(".widget_rss ul").addClass("media-list"),t("table#wp-calendar").addClass("table table-striped"),t(window).scroll(function(){t(this).scrollTop()>100?t(".scroll-to-top").fadeIn():t(".scroll-to-top").fadeOut()}),t(".scroll-to-top").click(function(){return t("html, body").animate({scrollTop:0},800),!1}),function(){var t=navigator.userAgent.toLowerCase().indexOf("webkit")>-1,e=navigator.userAgent.toLowerCase().indexOf("opera")>-1,n=navigator.userAgent.toLowerCase().indexOf("msie")>-1;(t||e||n)&&document.getElementById&&window.addEventListener&&window.addEventListener("hashchange",function(){var t,e=location.hash.substring(1);/^[A-z0-9_-]+$/.test(e)&&(t=document.getElementById(e),t&&(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus()))},!1)}()});
jQuery(window).load(function(){jQuery(".flexslider").length&&jQuery(".flexslider").flexslider({animation:"fade",controlNav:!0,prevText:"",nextText:"",smoothHeight:!0})});

**Comment by FreeWPTP** [comment]
Related topics :

https://colorlib.com/wp/forums/topic/dazzling-slider-spills-over-content-at-the-top/
https://colorlib.com/wp/forums/topic/text-stuck-under-slider-image-2/

**Comment by puikinsh** [comment]
Sorry for late response. 

This is now fixed in https://github.com/puikinsh/Dazzling/commit/b77704284eb644ee71aa2c11b5fa0bfcbe64ac4b
