### ISSUE TITLE
Untranslated string in options.php

### ISSUE THREAD

**Issue by vahalan** [puikinsh/Dazzling#2]
Hi

Theme shows All rights reserved at bottom row. It isn't on the .po file

In options.php:303: 'std' => '<a href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( get_bloginfo( 'name', 'display' ) ) . '" >' . get_bloginfo( 'name', 'display' ) . '</a>  All rights reserved.',

Please add to translatable strings, thanks.

Antti Vähälummukka

**Comment by puikinsh** [comment]
Actually this text can be changed via Theme Options - Footer - Footer information. 

Nevertheless, I updated Github version and the latest language files has this string added
