### ISSUE TITLE
Popular posts widget is not displaying posts in the correct order

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Dazzling#28]
Related Topic : https://wordpress.org/support/topic/bug-in-popular-post-widget?replies=1

**Comment by FreeWPTP** [comment]
Posted the solution here https://wordpress.org/support/topic/bug-in-popular-post-widget?replies=1#post-7592178

**Comment by puikinsh** [comment]
WordPress doesn't offer anly built-in analytics therefore popularity is determined based on number of comments and not views. Maybe it's not the most accurate way to display how popular are posts but it's the only one that we can get from WordPress without implementing our own tracking script.

**Comment by puikinsh** [comment]
I have now fixed this. Thanks @FreeWPTP 

More info here: https://github.com/puikinsh/Dazzling/commit/e8106832abaf07884f7f1edf81621becb34f00e4
