### ISSUE TITLE
PHP Fatal error after updating from 2.0.1 to 2.0.3

### ISSUE THREAD

**Issue by FireEmerald** [puikinsh/Dazzling#45]
Updated your theme from 2.0.1 to 2.0.3 and now there's only the following error returned, if the site is accessed:

```
PHP Fatal error:  Call to undefined function of_get_option() in /wp-content/themes/dazzling/inc/extras.php on line 121
```

Affected line is in [extras.php#L121](https://github.com/puikinsh/Dazzling/blame/master/inc/extras.php#L121)

Any idea what went wrong here?

**Comment by kurnias** [comment]
Got HTTP Error 500 after updating 2.0.1 to 2.0.3.

**Comment by puikinsh** [comment]
I am terribly sorry about this error. 
Fixed on: https://github.com/puikinsh/Dazzling/commit/f48e27e07162b1c167a18dc10f4671463cce32f7
