### ISSUE TITLE
Cannot use child combinator (>) in custom CSS

### ISSUE THREAD

**Issue by philip-peterson** [puikinsh/Dazzling#7]
Hello there,

Whenever I try to use a CSS rule that has a greater than sign (`>`) in it, after saving, the `>` gets transformed into `&gt;`. It also shows up that way in the HTML's STYLE tag, so the CSS rule doesn't work.

I think this must be something to do with the way the Options Framework sanitizes inputs (before serialization instead of after deserialization). Since they just made some updates to the way this is done in their latest version (1.8.3) I thought I would try updating, but it was to no avail.

Any thoughts on how this can be fixed?

**Comment by FreeWPTP** [comment]
In the latest version of theme all theme options are now moved to WordPress customizer that you can find in the admin area under Appearance >> Customize and this issue is no longer exist there.
