### ISSUE TITLE
Can Featured Image size be configured?

### ISSUE THREAD

**Issue by bilang** [puikinsh/Dazzling#9]
"Featured Image (Blog and Single Post) is set to 730 by 410 pixels."
It seems that the image will be scaled if it is not 16:9, so is there any chance to make this more flexible?
Featured Slider Image is OK.

Thanks

**Comment by puikinsh** [comment]
Image for featured images are set via this line of code that you can see here: https://github.com/puikinsh/Dazzling/blob/master/functions.php#L54

You can use any value you want just make sure to regenerate thumbnails if you already have images uploaded on your website. 

Images are not going to be scaled to look pixelated. They might be cropped and resized if needed but theme won't stretch those images.

**Comment by bilang** [comment]
yes, I did it this way already.

But I found that the theme will resize the image. If I use an image 1920 by 550 to get the best result of Featured Slider Image, the Featured Image (Blog and Single Post) will resize it to 730 by 410 , not cropping but resizing, making it a different scale image.

**Comment by puikinsh** [comment]
Then change the value for featured images inside functions.php file to match that aspect ratio. You can use something like 730px by 210px images.
